### ISSUE TITLE
Use The RoboRIO Hostname

### ISSUE THREAD

**Issue by mjmill** [FIRST-Team-2557-The-SOTABots/FRC_Robot2.0#14]
The youtube hostname is good for prototyping, but the hostname for the RoboRIO would be better.

https://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/242608-roborio-networking

The above link says:

roboRIO mDNS: roboRIO-####-FRC.local (where #### is your team number with no leading zeroes) You should be able to use this address to communicate with the roboRIO over either interface through ping, browser, etc.

So, a hostname of roboRIO-2557-FRC.local should work.

https://github.com/FIRST-Team-2557-The-SOTABots/FRC_Robot2.0/blob/3cc007571ec1ee8836c465c14ca1ee3d8da95e16/GetLatency/src/Detector.java#L11

**Comment by liloheinrich** [comment]
yes, roboRIO-2557-FRC.local or the IP of the roboRIO (10.25.57.2) should work

**Comment by mjmill** [comment]
It might not always be 10.25.57.2 - say if a certain pi gets assigned it first.  We should rely on mDNS and use the hostname instead of the IP.

**Comment by defied** [comment]
mDNS works great. We also use it for vision-pi.local. It's tricky to use in the pit, though, when working on the pi separate from the Rio.
